import { Mission } from "../../simulation/types";

export const pack1Missions: Mission[] = [
  {
    id: "p1-move-001",
    type: "move_hare",
    promptText: "Flytt haren til 3.",
    promptAudioKey: "p1_move_001",
    numberLine: { start: 0, end: 10, step: 1, showLabels: true, highlightTicks: [] },
    target: 3,
    choices: [],
    hint: "Tell tre skritt fra 0: 1, 2, 3.",
    reward: { stars: 1 },
  },
  {
    id: "p1-move-002",
    type: "move_hare",
    promptText: "Flytt haren til 7.",
    promptAudioKey: "p1_move_002",
    numberLine: { start: 0, end: 10, step: 1, showLabels: true, highlightTicks: [] },
    target: 7,
    choices: [],
    hint: "Start fra 0 og tell til 7.",
    reward: { stars: 1 },
  },
  {
    id: "p1-move-003",
    type: "move_hare",
    promptText: "Flytt haren til 5.",
    promptAudioKey: "p1_move_003",
    numberLine: { start: 0, end: 10, step: 1, showLabels: true, highlightTicks: [] },
    target: 5,
    choices: [],
    hint: "5 er midt på tallinja fra 0 til 10.",
    reward: { stars: 1 },
  },
  {
    id: "p1-fill-001",
    type: "fill_missing",
    promptText: "Hvilket tall mangler? 0, 1, 2, ?, 4, 5",
    promptAudioKey: "p1_fill_001",
    numberLine: { start: 0, end: 5, step: 1, showLabels: true, highlightTicks: [3] },
    target: 3,
    choices: [2, 3, 5],
    hint: "Mellom 2 og 4 er det ett tall.",
    reward: { stars: 1 },
  },
  {
    id: "p1-fill-002",
    type: "fill_missing",
    promptText: "Hvilket tall mangler? 6, 7, ?, 9, 10",
    promptAudioKey: "p1_fill_002",
    numberLine: { start: 6, end: 10, step: 1, showLabels: true, highlightTicks: [8] },
    target: 8,
    choices: [7, 8, 9],
    hint: "Mellom 7 og 9 er det ett tall.",
    reward: { stars: 1 },
  },
  {
    id: "p1-move-004",
    type: "move_hare",
    promptText: "Flytt haren til 1.",
    promptAudioKey: "p1_move_004",
    numberLine: { start: 0, end: 10, step: 1, showLabels: true, highlightTicks: [] },
    target: 1,
    choices: [],
    hint: "1 er rett etter 0.",
    reward: { stars: 1 },
  },
  {
    id: "p1-move-005",
    type: "move_hare",
    promptText: "Flytt haren til 10.",
    promptAudioKey: "p1_move_005",
    numberLine: { start: 0, end: 10, step: 1, showLabels: true, highlightTicks: [] },
    target: 10,
    choices: [],
    hint: "10 er helt på slutten av tallinja.",
    reward: { stars: 1 },
  },
  {
    id: "p1-fill-003",
    type: "fill_missing",
    promptText: "Hvilket tall mangler? 0, ?, 2, 3, 4",
    promptAudioKey: "p1_fill_003",
    numberLine: { start: 0, end: 4, step: 1, showLabels: true, highlightTicks: [1] },
    target: 1,
    choices: [1, 3, 4],
    hint: "Mellom 0 og 2 er det ett tall.",
    reward: { stars: 1 },
  },
];
