import { Mission } from "../../simulation/types";

export const pack3Missions: Mission[] = [
  {
    id: "p3-move-001",
    type: "move_hare",
    promptText: "Tallinja starter på 10. Flytt haren til 15.",
    promptAudioKey: "p3_move_001",
    numberLine: { start: 10, end: 30, step: 1, showLabels: true, highlightTicks: [] },
    target: 15,
    choices: [],
    hint: "Tell fra 10: 11, 12, 13, 14, 15.",
    reward: { stars: 1 },
  },
  {
    id: "p3-predict-001",
    type: "predict_jump",
    promptText: "Haren står på 20 og hopper 5 om gangen. Hvor lander den nå?",
    promptAudioKey: "p3_predict_001",
    numberLine: { start: 10, end: 30, step: 5, showLabels: true, highlightTicks: [20] },
    target: 25,
    choices: [23, 25, 30],
    hint: "20 pluss 5 er?",
    reward: { stars: 1 },
  },
  {
    id: "p3-fill-001",
    type: "fill_missing",
    promptText: "Tallinja hopper 5. Hvilket tall mangler? 10, 15, ?, 25, 30",
    promptAudioKey: "p3_fill_001",
    numberLine: { start: 10, end: 30, step: 5, showLabels: true, highlightTicks: [20] },
    target: 20,
    choices: [18, 20, 22],
    hint: "Etter 15 hopper vi 5 til: 15 + 5 = ?",
    reward: { stars: 1 },
  },
  {
    id: "p3-spot-001",
    type: "spot_error",
    promptText:
      "Ser du feilen? Tallinja skal hoppe 2 om gangen: 10, 12, 14, 17, 18. Trykk på feil-tallet.",
    promptAudioKey: "p3_spot_001",
    numberLine: { start: 10, end: 18, step: 2, showLabels: true, highlightTicks: [] },
    target: 3,
    choices: [10, 12, 14, 17, 18],
    errorTicks: [17],
    hint: "Se nøye på hvert hopp. Er alle hoppene like store?",
    reward: { stars: 1 },
  },
  {
    id: "p3-fill-002",
    type: "fill_missing",
    promptText: "Tallinja hopper 2. Hvilket tall mangler? 10, 12, ?, 16, 18",
    promptAudioKey: "p3_fill_002",
    numberLine: { start: 10, end: 18, step: 2, showLabels: true, highlightTicks: [14] },
    target: 14,
    choices: [13, 14, 15],
    hint: "Etter 12 hopper vi 2 til: 12 + 2 = ?",
    reward: { stars: 1 },
  },
  {
    id: "p3-predict-002",
    type: "predict_jump",
    promptText: "Haren står på 15 og hopper 5 om gangen. Hvor lander den nå?",
    promptAudioKey: "p3_predict_002",
    numberLine: { start: 10, end: 30, step: 5, showLabels: true, highlightTicks: [15] },
    target: 20,
    choices: [18, 20, 25],
    hint: "15 pluss 5 er?",
    reward: { stars: 1 },
  },
  {
    id: "p3-move-002",
    type: "move_hare",
    promptText: "Tallinja starter på 10. Flytt haren til 25.",
    promptAudioKey: "p3_move_002",
    numberLine: { start: 10, end: 30, step: 5, showLabels: true, highlightTicks: [] },
    target: 25,
    choices: [],
    hint: "10, 15, 20, 25 — tell hoppene på 5.",
    reward: { stars: 1 },
  },
  {
    id: "p3-spot-002",
    type: "spot_error",
    promptText: "Tallinja skal hoppe 5: 10, 15, 20, 24, 30. Trykk på feil-tallet.",
    promptAudioKey: "p3_spot_002",
    numberLine: { start: 10, end: 30, step: 5, showLabels: true, highlightTicks: [] },
    target: 3,
    choices: [10, 15, 20, 24, 30],
    errorTicks: [24],
    hint: "Etter 20 skal neste hopp på 5 lande på 25.",
    reward: { stars: 1 },
  },
];
