import { Mission } from "../../simulation/types";

export const pack4Missions: Mission[] = [
  {
    id: "p4-build-001",
    type: "build_line",
    promptText: "Lag en tallinje fra 0 til 10 som hopper 1 om gangen.",
    promptAudioKey: "p4_build_001",
    numberLine: { start: 0, end: 10, step: 1, showLabels: true, highlightTicks: [] },
    target: null,
    choices: [],
    hint: "Start på 0, slutt på 10, hopp på 1.",
    reward: { stars: 1 },
  },
  {
    id: "p4-build-002",
    type: "build_line",
    promptText: "Lag en tallinje fra 0 til 10 som hopper 2 om gangen.",
    promptAudioKey: "p4_build_002",
    numberLine: { start: 0, end: 10, step: 2, showLabels: true, highlightTicks: [] },
    target: null,
    choices: [],
    hint: "Start på 0, slutt på 10, hopp på 2.",
    reward: { stars: 1 },
  },
  {
    id: "p4-build-003",
    type: "build_line",
    promptText: "Lag en tallinje fra 10 til 30 som hopper 5 om gangen.",
    promptAudioKey: "p4_build_003",
    numberLine: { start: 10, end: 30, step: 5, showLabels: true, highlightTicks: [] },
    target: null,
    choices: [],
    hint: "Start på 10, slutt på 30, hopp på 5.",
    reward: { stars: 1 },
  },
  {
    id: "p4-build-004",
    type: "build_line",
    promptText: "Lag en tallinje fra 0 til 20 som hopper 2 om gangen.",
    promptAudioKey: "p4_build_004",
    numberLine: { start: 0, end: 20, step: 2, showLabels: true, highlightTicks: [] },
    target: null,
    choices: [],
    hint: "Start på 0, slutt på 20, hopp på 2.",
    reward: { stars: 1 },
  },
  {
    id: "p4-build-005",
    type: "build_line",
    promptText: "Lag en tallinje fra 5 til 25 som hopper 5 om gangen.",
    promptAudioKey: "p4_build_005",
    numberLine: { start: 5, end: 25, step: 5, showLabels: true, highlightTicks: [] },
    target: null,
    choices: [],
    hint: "Start på 5, slutt på 25, hopp på 5.",
    reward: { stars: 1 },
  },
  {
    id: "p4-build-006",
    type: "build_line",
    promptText: "Lag en tallinje fra 10 til 20 som hopper 2 om gangen.",
    promptAudioKey: "p4_build_006",
    numberLine: { start: 10, end: 20, step: 2, showLabels: true, highlightTicks: [] },
    target: null,
    choices: [],
    hint: "Start på 10, slutt på 20, hopp på 2.",
    reward: { stars: 1 },
  },
];
