import { Mission } from "../../simulation/types";

export const pack2Missions: Mission[] = [
  {
    id: "p2-predict-001",
    type: "predict_jump",
    promptText: "Haren står på 10 og hopper 2 om gangen. Hvor lander den nå?",
    promptAudioKey: "p2_predict_001",
    numberLine: { start: 0, end: 20, step: 2, showLabels: true, highlightTicks: [10] },
    target: 12,
    choices: [11, 12, 14],
    hint: "Tell to skritt fram fra 10.",
    reward: { stars: 1 },
  },
  {
    id: "p2-predict-002",
    type: "predict_jump",
    promptText: "Haren står på 4 og hopper 2 om gangen. Hvor lander den nå?",
    promptAudioKey: "p2_predict_002",
    numberLine: { start: 0, end: 20, step: 2, showLabels: true, highlightTicks: [4] },
    target: 6,
    choices: [5, 6, 8],
    hint: "4 pluss 2 er?",
    reward: { stars: 1 },
  },
  {
    id: "p2-move-001",
    type: "move_hare",
    promptText: "Flytt haren til 14.",
    promptAudioKey: "p2_move_001",
    numberLine: { start: 0, end: 20, step: 1, showLabels: true, highlightTicks: [] },
    target: 14,
    choices: [],
    hint: "Tell fra 10: 11, 12, 13, 14.",
    reward: { stars: 1 },
  },
  {
    id: "p2-fill-001",
    type: "fill_missing",
    promptText: "Tallinja hopper 2 om gangen. Hvilket tall mangler? 0, 2, 4, ?, 8",
    promptAudioKey: "p2_fill_001",
    numberLine: { start: 0, end: 8, step: 2, showLabels: true, highlightTicks: [6] },
    target: 6,
    choices: [5, 6, 7],
    hint: "Etter 4 hopper vi 2 til: 4 + 2 = ?",
    reward: { stars: 1 },
  },
  {
    id: "p2-predict-003",
    type: "predict_jump",
    promptText: "Haren står på 16 og hopper 2 om gangen. Hvor lander den nå?",
    promptAudioKey: "p2_predict_003",
    numberLine: { start: 0, end: 20, step: 2, showLabels: true, highlightTicks: [16] },
    target: 18,
    choices: [17, 18, 20],
    hint: "16 pluss 2 er?",
    reward: { stars: 1 },
  },
  {
    id: "p2-move-002",
    type: "move_hare",
    promptText: "Flytt haren til 20.",
    promptAudioKey: "p2_move_002",
    numberLine: { start: 0, end: 20, step: 1, showLabels: true, highlightTicks: [] },
    target: 20,
    choices: [],
    hint: "20 er helt på slutten av tallinja.",
    reward: { stars: 1 },
  },
  {
    id: "p2-fill-002",
    type: "fill_missing",
    promptText: "Tallinja hopper 2. Hvilket tall mangler? 10, 12, 14, ?, 18",
    promptAudioKey: "p2_fill_002",
    numberLine: { start: 10, end: 18, step: 2, showLabels: true, highlightTicks: [16] },
    target: 16,
    choices: [15, 16, 17],
    hint: "Etter 14 hopper vi 2 til: 14 + 2 = ?",
    reward: { stars: 1 },
  },
  {
    id: "p2-predict-004",
    type: "predict_jump",
    promptText: "Haren står på 0 og hopper 2 om gangen. Hvor lander den nå?",
    promptAudioKey: "p2_predict_004",
    numberLine: { start: 0, end: 20, step: 2, showLabels: true, highlightTicks: [0] },
    target: 2,
    choices: [1, 2, 4],
    hint: "0 pluss 2 er?",
    reward: { stars: 1 },
  },
];
